version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOSTNAME=127.0.0.1
  database:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=Dev
      - POSTGRES_PASSWORD=bliblabloubliblui
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
