version: '3'
services:
  api:
    build: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/go/src/CEToolBox/api
    environment:
      MONGO_INITDB_ROOT_USERNAME: cetoolbox
      MONGO_INITDB_ROOT_PASSWORD: azertyuiop
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    command: reflex -r '\.go$$' -s -- sh -c 'go build . && ./CEToolBox'
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cetoolbox
      MONGO_INITDB_ROOT_PASSWORD: azertyuiop
