version: '3'
services:
  database:
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=Dev
      - POSTGRES_PASSWORD=bliblabloubliblui
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "9999:9999"
    environment:
      - PORT=9999
      - HOSTNAME=localhost
      - PGUSER=Dev
      - PGPASSWORD=bliblabloubliblui
    depends_on:
      - database
volumes:
  db:
    driver: local
